# Generated by Django 5.0.6 on 2024-06-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_alter_logentry_user'),
        ('core', '0013_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
